### ISSUE TITLE
Missing dependency `chai`

### ISSUE THREAD

**Issue by trevor-scheer** [oclif/test#248]
Error: `Cannot find module 'chai' from '../../node_modules/@oclif/test/lib/exit.js'`

This makes sense: `chai` is listed as a dev dependency but it's used during oclif's runtime. I'd open a PR but I'm unsure if `chai` ought to be a peer dependency or a regular dependency.

**Comment by RodEsp** [comment]
Heya @trevor-scheer, where are you seeing this used during oclif's runtime?
Since chai is only a testing framework I don't think that should be the case.

**Comment by trevor-scheer** [comment]
Looks to be imported [here](https://github.com/oclif/test/blob/main/src/exit.ts#L1).

In the built js this results in:
`const chai_1 = require("chai");`

**Comment by trevor-scheer** [comment]
Hey @RodEsp, can you let me know if you agree with my last comment? If not, am I misunderstanding the expected use case for this function / should it not be publicly exported at all maybe?

**Comment by RodEsp** [comment]
Heya @trevor-scheer, sorry for the delayed response.
You're right that chai is imported there but that shouldn't run when you are running commands in an oclif cli.

What is it you are trying to do that results in you getting the error, `Cannot find module 'chai'...`?

**Comment by phil-lgr** [comment]
I think it should be listed in "dependencies", running tests that use:

```
import { test } from '@oclif/test';
```

will require "chai"
