### ISSUE TITLE
chai should be a dependency

### ISSUE THREAD

**Issue by decentralion** [oclif/test#32]
Chai is currently listed in the package.json [as a dev dependency](https://github.com/oclif/test/blob/master/package.json#L18). However, it [is depended on in the source code](https://github.com/oclif/test/blob/master/src/exit.ts#L1). So, it should be an actual dependency.

**Comment by jdxcode** [comment]
I don't want to include it so it behaves more like a peerDependency.

**Comment by bendrucker** [comment]
Hey, any particular reason you want the user to supply this? Unlike something like mocha, there's nothing global or conflicting about chai. I don't care if there are multiple versions of chai being loaded.

**Comment by BrutalSimplicity** [comment]
Is this documented somewhere? Completely breaks in `jest` without the `chai` peer dependency.
