### ISSUE TITLE
Command testing does not work well with flags containing spaces

### ISSUE THREAD

**Issue by mattwiller** [oclif/test#35]
I'm trying to test a command that takes in a flag whose value may contain spaces, e.g. `--flag="multiple words"`.  In this example, `flag` has two possible options defined: `'multiple words'` and `'singleword'`.  This seems to work fine when doing manual testing, but I'm having a hard time using the test utilities to write an automated test for this case.  I've tried something like the following without success:

```js
test
    .stdout()
    .command([
        'foo:bar',
        '--flag="multiple words"'
    ])
    .it('should work with spaces', ctx => {
        // asserts go here
    });
```

The flag has a set of options it may take, and I see an error that "multiple words" is not one of the options even though it definitely is.

I suspect this is related, but I also cannot specify the flag as `--flag singleword` inside of `.command()` — I get an error like `Unexpected argument: --flag singleword`.  Doing `--flag=singleword` works fine in the test.

**Comment by jdxcode** [comment]
use `--flag=multiple words`
