### ISSUE TITLE
When calling `error` I would expect the mocked `stderr` to have data

### ISSUE THREAD

**Issue by wprater** [oclif/test#38]
Trying to write tests around failing commands and I cannot seem to get data to be present in the mocked stderr.  Any ideas?

Both `stderr` and `stdout` are empty when I exec `this.error('foo');` in the examples below.

```
describe('create handling failures', () => {
  test
    .stdout()
    .stderr()
    .command(['create'])
    .exit(2)
    .it('runs create', ctx => {
      expect(ctx.stderr).to.contain('foo');
    });
});
```

```
  2) create handling failures
       runs create:
     AssertionError: expected '' to include 'foo'
      at Context.test.nock.stdout.stderr.command.exit.it.ctx (test/commands/create.test.js:39:29)
      at Object.run (node_modules/fancy-test/lib/base.js:27:38)
      at Context.run (node_modules/fancy-test/lib/base.js:50:36)
```

Seems similar to the issue here https://github.com/oclif/oclif/issues/142

**Comment by sthuber90** [comment]
It would be a great feature to be able to assert exit code and stderr output. As far as I know you can get output of `stderr` from `this.error`, if you write 
```
this.error('Message', { exit: false })
this.error(err, { exit: 100 })
```

The test will then look like this:
```
test
    .stdout()
    .stderr()
    .command(['mycmd'])
    .exit(100)
    .it('runs mycmd', ctx => {
      expect(ctx.stderr).to.contain('Error: Message')
      expect(ctx.stdout).to.equal('')
    })
```

Maybe this will help someone ending up on this issue as well.

**Comment by vedantgoyal** [comment]
The way I'm getting around this is stubbing the error and then throwing a new error again in the test with the same msg.
`describe('run command', () => {
  let errorStub = [Run.prototype, 'error', (msg: string, _: any) => { throw new Error(msg) }]  

test
    .stub(...errorStub)
    .command(['run', 'arg1'])
    .catch(err => expect(err.message).to.contain('Invalid argument'))
    .it('invalid argument throws error with helpful message)`

**Comment by rori4** [comment]
@vedantgoyal  Where do you import the `Run` object from?

**Comment by rori4** [comment]
I figured it out. I imported `const { default: Command } = require('@oclif/command')` and passed `Command.prototype`
