### ISSUE TITLE
Support subsequent input after call a cammand

### ISSUE THREAD

**Issue by AlexZhenWang** [oclif/test#41]
Hi, I am using this awesome testing tool for my oclif project. Just wondering, my command will require password after running, is there any way I can pass the password to that command in the test.

More exactly, in my test case

> test
     .command(['needpassword'])
     // I need to pass password into the cli
     .it(ctx => {
        // expect
     })

I found there is no way I can pass my password in after calling the command. 

Any idea will be appreciated.

**Comment by ivome** [comment]
I ran into the same issue and ended up creating stubs for the inquirer instead in a custom plugin. Not ideal, but that works okay.
